# Lang
language: zh-cn

# Dark Mode
dark: false

# Header
menu:
  Home: /
  Archives: /archives
  Wiki: /memos
  About: /about

# Your Feed Location
#rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: Qian Hu
description: I'm a student, majoring in software engnieering, and now I'm focus on NLP. This blog is meant to help me expain things more precisely, and I hope what I post will help you understand things more clearly, this is my ultimate goal.

# Load fontawesome icons? Also see the links option
icons: false

# Footer area links
# NOTICE) If you set "icons: false" link names will be clear text
# If "icons: true" link names will interpreted as fontawesome icon names
# NOTICE) Use the fontawesome icon names without the fa- prefix (http://fontawesome.io/cheatsheet/)
links:
  Blog: /archives/
  Wiki: /memos/
  Github: https://github.com/CSSE-NULL/
  About: /about  

# nav position (top, left. top is default)
nav: left

# Info
archive_footer_content: Understand things clearly, and explain them well.
post_footer_content: Understand things clearly, and explain them well.

# Gitment
gitment:
  owner: 
  repo: 
  client:
    id: 
    secret: 

# Utterances
# NOTICE) make sure the app is installed on the repo before using this commit system
# see https://utteranc.es/ for more
utterances:
  enable: false
  repo: # your repo in this format: 'username/reponame', note that there is no '.git' suffix

# If you want to use valine,you should get the appId and appKey form https://leancloud.cn ,more setting please see https://valine.js.org
valine:
  enable: true # !!if you want use valine comment system,please set enable: true
  appId: 7gzxQSBU9E7feQRDYRQ5uucC-gzGzoHsz #your leancloud appId
  appKey: STpRQGYWwk94qyKYBxUBmUME  #your leancloud appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: 你想说点啥？ # valine comment input placeholder(like: Please leave your footprints )
  avatar: monsterid # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: true # valine mail notify (true/false)
  visitor: true # show the number of visitors
  lang: zh-cn


# add post views
leancloud_visitors:
 enable: true
 app_id:  7gzxQSBU9E7feQRDYRQ5uucC-gzGzoHsz
 app_key: STpRQGYWwk94qyKYBxUBmUME

# MathJax Support
# mathjax:
#   enable: true
#   per_page: true
#   #cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
#   cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Donate
donate:
  enable: false
  github: https://github.com/CSSE-NULL
  paypal: 
  bitcoin:
  BTCQR:
  AliPayQR:
  WeChatQR:
